import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {createImportedCreature} from '../src/imported-creature.js';
function asset(){const scene=new THREE.Group(),bone=new THREE.Bone();bone.name='Leg';const geometry=new THREE.BoxGeometry(.6,1,.8),count=geometry.attributes.position.count;geometry.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(new Uint16Array(count*4),4));const weights=new Float32Array(count*4);for(let i=0;i<count;i++)weights[i*4]=1;geometry.setAttribute('skinWeight',new THREE.Float32BufferAttribute(weights,4));const mesh=new THREE.SkinnedMesh(geometry,new THREE.MeshStandardMaterial());mesh.position.y=.5;mesh.add(bone);mesh.bind(new THREE.Skeleton([bone]));scene.add(mesh);scene.updateMatrixWorld(true);return {scene,animations:[new THREE.AnimationClip('Walk',1,[new THREE.QuaternionKeyframeTrack('Leg.quaternion',[0,.5,1],[0,0,0,1,.2,0,0,Math.sqrt(.96),0,0,0,1])])]};}
test('generated preview and room get independent skeletons, grounded scale and motion',()=>{const source=asset(),studio=createImportedCreature(source),room=createImportedCreature(source);const a=studio.character.getObjectByName('Leg'),b=room.character.getObjectByName('Leg');assert.notEqual(a,b);const bounds=new THREE.Box3().setFromObject(room.group);assert.ok(Math.abs(bounds.min.y)<1e-6);assert.ok(Math.abs(bounds.max.y-.55)<1e-6);studio.animate(.25,.22);assert.notEqual(a.quaternion.x,b.quaternion.x);const before=b.quaternion.clone();room.animate(.25,0);assert.ok(b.quaternion.equals(before));assert.equal(studio.triangles,12);studio.dispose();room.animate(.1,.22);assert.notEqual(b.quaternion.x,0);room.dispose();});
test('generated pets reject missing rigs or animations before entering room mode',()=>{const source=asset();assert.throws(()=>createImportedCreature({...source,animations:[]}),/walking animation/);source.scene.clear();source.scene.add(new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial()));assert.throws(()=>createImportedCreature(source),/skinned mesh/);});


test('translated source rigs remain grounded after normalisation',()=>{const source=asset();source.scene.position.y=.411;source.scene.updateMatrixWorld(true);const pet=createImportedCreature(source);pet.group.updateMatrixWorld(true);pet.group.traverse(o=>{if(o.isSkinnedMesh)o.computeBoundingBox();});const box=new THREE.Box3().setFromObject(pet.group);assert.ok(Math.abs(box.min.y)<1e-6);assert.ok(Math.abs(box.max.y-.55)<1e-6);pet.dispose();});
test('incomplete quadruped limb chains are refused instead of silently playing a partial gait',()=>{const source=asset();source.scene.getObjectByName('Leg').name='tripo0_Right_Limb_0';assert.throws(()=>createImportedCreature(source),/incomplete leg rig/);});
