import {chromium,devices} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile,mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createApp} from '../server.mjs';
await mkdir('artifacts',{recursive:true});const dir=await mkdtemp(join(tmpdir(),'creature-browser-'));const app=await createApp({env:{DATA_DIR:dir}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});const results=[];
try {
 const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>window.creatureLab);await page.waitForFunction(()=>document.querySelector('#creation-note').textContent.includes('Local design demo'));
 await page.locator('[data-preset="Mochi"]').click();await page.locator('#create-button').click();await page.waitForFunction(()=>window.creatureLab.snapshot().pet.source==='local');assert.equal((await page.evaluate(()=>window.creatureLab.snapshot())).pet.design.family,'bunny');
 await page.reload();await page.waitForFunction(()=>window.creatureLab);await page.locator('.saved-card').filter({hasText:'Mochi'}).click();assert.equal((await page.evaluate(()=>window.creatureLab.snapshot())).pet.name,'Mochi');
 await page.locator('[data-preset="Nova"]').click();await page.waitForFunction(()=>window.creatureLab.snapshot().external);await page.screenshot({path:'artifacts/desktop.png',fullPage:true});await page.locator('#viewport').screenshot({path:'artifacts/pet.png'});
 await page.locator('#ball-button').click();await page.waitForFunction(()=>window.creatureLab.snapshot().motion.ball);const start=await page.evaluate(()=>window.creatureLab.snapshot().position);await page.waitForFunction(s=>{const p=window.creatureLab.snapshot().position;return Math.hypot(p.x-s.x,p.z-s.z)>.04;},start);await page.locator('#rest-button').click();assert.equal((await page.evaluate(()=>window.creatureLab.snapshot())).motion.action,'rest');await page.locator('#follow-button').click();assert.equal((await page.evaluate(()=>window.creatureLab.snapshot())).motion.follow,true);
 await page.locator('#pet-description').fill('A moss cat with green eyes, small ears and a fluffy tail. Shy and slender.');await page.locator('#demo-button').click();await page.waitForFunction(()=>window.creatureLab.snapshot().pet.design.coat==='moss');const glb=await page.evaluate(async()=>Array.from(new Uint8Array(await window.creatureLab.exportGLB())));const binary=Buffer.from(glb);assert.equal(binary.readUInt32LE(0),0x46546c67);const length=binary.readUInt32LE(12);const document=JSON.parse(binary.subarray(20,20+length).toString());assert.equal(document.animations.length,2);assert.equal(document.animations[0].channels.length,4);await writeFile('artifacts/nova.glb',binary);
 const vision=await page.evaluate(()=>new Promise((resolve,reject)=>{const worker=new Worker('/perception-worker.js');const timer=setTimeout(()=>{worker.terminate();reject(new Error('Vision timeout'));},20000);worker.onmessage=async({data})=>{if(data.type==='ready'){const canvas=new OffscreenCanvas(320,240),ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,320,240);const bitmap=canvas.transferToImageBitmap();worker.postMessage({type:'frame',bitmap},[bitmap]);}if(data.type==='result'||data.type==='error'){clearTimeout(timer);worker.terminate();resolve(data);}};worker.onerror=e=>{clearTimeout(timer);worker.terminate();reject(new Error(e.message));};worker.postMessage({type:'start'});}));assert.equal(vision.type,'result',vision.message);assert.equal(vision.visible,false);
 assert.deepEqual(errors,[]);results.push({desktop:'passed',creation:'local mode',saveReload:true,virtualFetch:true,restFollow:true,glbAnimations:2,localVision:'real model / blank frame negative case'});await page.close();
 for(const device of ['iPhone 13','Pixel 7']){const context=await browser.newContext({...devices[device]});const mobile=await context.newPage();await mobile.goto(base);await mobile.waitForFunction(()=>window.creatureLab);assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mobile.locator('#create').scrollIntoViewIfNeeded();await mobile.screenshot({path:`artifacts/${device.replaceAll(' ','-')}.png`});await mobile.locator('[data-preset="Mochi"]').click();await mobile.locator('#create-button').click();await mobile.waitForFunction(()=>window.creatureLab.snapshot().pet.source==='local');assert.equal((await mobile.evaluate(()=>window.creatureLab.snapshot())).pet.design.family,'bunny');results.push({device,responsive:true,creation:true,physicalAR:'not tested'});await context.close();}
 await writeFile('artifacts/browser-checks.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser.close();await app.close();await rm(dir,{recursive:true,force:true});}
