import './style.css';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';
import { loadCreatureAsset, createImportedCreature } from './imported-creature.js';
import { PRESETS, NOVA, localDesign, validateDesign, includedModel, currentModelUrl } from '../shared/design.mjs';
import { PetMotion, LABELS, fallbackDecision, allowedActions } from '../shared/motion.mjs';
import { Studio } from './view.js';
import { RoomSession, mobileARSupport } from './ar.js';
import { Perception } from './perception.js';
const paw='<svg viewBox="0 0 32 32" aria-hidden="true"><ellipse cx="16" cy="22" rx="8" ry="6"/><ellipse cx="7" cy="13" rx="3" ry="4"/><ellipse cx="14" cy="8" rx="3" ry="4"/><ellipse cx="22" cy="9" rx="3" ry="4"/><ellipse cx="27" cy="16" rx="3" ry="4"/></svg>';
const arrow='<span aria-hidden="true">↗</span>';
document.querySelector('#app').innerHTML=`
<header class="topbar"><a class="brand" href="#">${paw}<span>AI CONCEPT LAB <b>// 3D LAB</b></span></a><span class="edition">EXPERIMENT 006</span><a class="nav-link" href="#create">Meet your companion ${arrow}</a></header>
<main>
  <section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow"><span class="spark">✦</span> IMAGINATION, WITH A LITTLE PERSONALITY</p><h1 id="hero-title">Describe a creature.<br><em>Bring it into your room.</em></h1><p>A tiny companion. Your own design.<br>A little world of play, through your phone camera.</p><a href="#create" class="hero-link">Let’s meet your creature <span>↓</span></a></div><span class="art-label">CONCEPT ARTWORK</span><span class="hero-name">NOVA <i>curious by nature</i></span></section>
  <section class="workspace" id="create" aria-label="Create and play">
    <div class="creator card"><div class="card-heading"><span class="step">01</span><div><p class="eyebrow">MAKE IT YOURS</p><h2>Who’s your little friend?</h2></div></div>
      <form id="pet-form"><label for="pet-name">A name to call them</label><input id="pet-name" name="name" value="Nova" maxlength="32" autocomplete="off" required><label for="pet-description">Describe your companion</label><textarea id="pet-description" name="description" maxlength="1200" minlength="12" required>${PRESETS[0].description}</textarea><p class="field-hint">Fox, cat or bunny. Tell us the colours, ears, tail and personality you imagine.</p><div class="suggestions" aria-label="Try a description">${PRESETS.map(p=>`<button class="suggestion" type="button" data-preset="${p.name}">${p.name} <span>↗</span></button>`).join('')}</div><button class="primary" id="create-button" type="submit"><span>✦</span> Create my companion <span>→</span></button><button id="demo-button" type="button" class="demo-button">Try the local demo</button><p class="connection-note" id="creation-note">Checking the connection…</p></form>
      <div class="access" id="access" hidden><label for="access-code">This workshop needs an access code</label><div class="access-row"><input id="access-code" type="password" autocomplete="current-password" placeholder="Access code"><button id="unlock" type="button">Unlock</button></div></div>
      <p class="form-status" id="form-status" role="status" aria-live="polite"></p>
      <details class="upgrade" id="upgrade"><summary>Your detailed companion</summary><p>Approve the character artwork before building 3D. We then add four-paw motion, head poses, expressions, jaw animation and stepping turns. New faces need visual review.</p><button id="tripo-start" type="button" class="outline">Create a reference</button><div id="generation-status" role="status"></div><img id="reference-image" alt="Generated pet reference" hidden><button id="approve-reference" type="button" class="outline" hidden>Approve & build 3D</button><button id="use-model" type="button" class="outline" hidden>Meet the generated pet</button><button id="retry-finish" type="button" class="outline" hidden>Retry animation finishing · no credits</button><p id="tripo-note" class="field-hint"></p></details>
    </div>
    <div class="preview card"><div class="preview-heading"><div><p class="eyebrow">YOUR COMPANION</p><h2 id="preview-name">Meet Nova <span>✦</span></h2></div><span class="mode-tag" id="preview-tag">LIVE 3D PREVIEW</span></div><div class="viewport" id="viewport" role="region" aria-label="Interactive animated pet preview"><div id="studio" class="studio"></div><div id="model-loading" class="model-loading" role="status" hidden>Preparing your detailed companion…</div><div class="viewport-top"><span class="pet-trait" id="pet-trait">Curious little fox</span><button id="reset-view" class="icon-button" aria-label="Reset preview camera" title="Reset camera">↻</button></div><div class="viewport-bottom"><span class="pulse-dot"></span><span id="action-label">Taking it all in</span><span class="viewport-hint">Drag to look around · tap to play</span></div></div>
      <div class="play-tools"><button id="ball-button" type="button">◉ <span>Throw a ball</span></button><button id="follow-button" type="button" aria-pressed="false">⌁ <span>Follow me</span></button><button id="rest-button" type="button">☾ <span>Rest</span></button><button id="block-button" type="button" aria-pressed="false">▧ <span>Mark an obstacle</span></button></div>
      <div class="expression-tools"><span>Set the mood</span><div class="mood-options" role="group" aria-label="Companion mood"><button type="button" data-mood="curious" aria-pressed="false">Curious</button><button type="button" data-mood="playful" aria-pressed="false">Playful</button><button type="button" data-mood="shy" aria-pressed="false">Shy</button><button type="button" data-mood="sleepy" aria-pressed="false">Sleepy</button></div><div class="reaction-options"><button id="greet-button" type="button">✦ Say hello</button><button id="stretch-button" type="button">↔ Stretch</button><button id="pet-button" type="button">♡ Give affection</button></div><p id="mood-note" aria-live="polite">Body language makes every little reaction different.</p></div><div class="pet-footer"><div class="energy"><span>Play energy <b id="energy-value">82%</b></span><div class="energy-track"><i id="energy-fill"></i></div></div><button class="room-button" id="room-button" type="button">Bring into my room ${arrow}</button></div>
      <div class="download-tools"><button id="download-pet" type="button">↓ Download 3D pet</button><button id="download-recipe" type="button">↓ Save design</button></div><p class="room-note" id="room-note">Open on your phone, allow the camera and place your pet on the floor.</p>
      <details class="mind"><summary><span class="pulse-dot"></span> A peek at their next move <span id="brain-source">Local behaviour</span></summary><div id="decision-body"><p>Decisions will appear here as you play.</p></div></details>
    </div>
  </section>
  <section class="saved-section"><div class="section-title"><div><p class="eyebrow">YOUR LITTLE UNIVERSE</p><h2>Friends to come back to.</h2></div><span>Saved on this device</span></div><div id="saved-pets" class="saved-pets"></div></section>
  <section class="how"><div><span>01 / DREAM</span><h3>A description becomes a design.</h3><p>Your words shape a supported creature, its colours and personality.</p></div><div><span>02 / MEET</span><h3>Watch it come to life.</h3><p>Explore the animated 3D preview. Follow, rest and play fetch.</p></div><div><span>03 / PLAY</span><h3>Your room becomes its playground.</h3><p>Place it on a tracked floor with a compatible mobile browser.</p></div></section>
</main><footer><span>AI CONCEPT LAB // 3D LAB // 006</span><span>An experiment in virtual companionship.</span><a href="https://8thwall.org" target="_blank" rel="noreferrer">8th Wall © 2026 Niantic Spatial</a><a href="/licenses/8thwall.txt">XR engine licence · provided as is</a></footer>
<div class="toast" id="toast" role="status" aria-live="polite" hidden></div>
<div class="room-view" id="room-view" hidden><canvas id="room-canvas"></canvas><div class="room-top"><span class="room-brand">AI CONCEPT LAB <b>// 3D LAB</b></span><button id="exit-room" type="button" aria-label="Exit camera view">✕</button></div><div class="room-instruction" id="room-instruction" role="status">Loading room tracking…</div><div class="room-controls"><button id="room-ball" type="button">◉ Ball</button><button id="room-follow" type="button" aria-pressed="false">⌁ Follow</button><button id="room-block" type="button">▧ Obstacle</button><button id="room-recenter" type="button">↻ Rescan</button><button id="room-greet" type="button">✦ Hello</button><button id="room-playful" type="button">♡ Play</button><button id="room-sleepy" type="button">☾ Sleepy</button><button id="room-vision" type="button" aria-pressed="false">◎ Notice people</button></div></div>`;
const $=id=>document.getElementById(id);
let pet={name:'Nova',description:PRESETS[0].description,design:{...NOVA},source:'sample'},motion=new PetMotion(),studio,room=null,config=null,petRevision=0,pendingDecision=false,lastDecision=0,lastUi=0,blockMode=false,toastTimer,saved=[],generation=null,generationTimer,externalPet=null,pendingBrief=null,generationStarting=false;
try{saved=JSON.parse(localStorage.getItem('creature-pets')||'[]').filter(p=>{try{validateDesign(p.design);return typeof p.name==='string'&&p.name.length<=32;}catch{return false;}}).slice(0,12);}catch{}
const toast=(message)=>{$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);};
async function api(path,body){const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await response.json();}catch{throw new Error('The workshop could not be reached. Please try again.');}if(!response.ok)throw new Error(data.error||'Something went wrong.');return data;}
async function connect(){config=await api('/api/config');if(!config.authorised&&!config.authRequired){await api('/api/session',{});config=await api('/api/config');}$('access').hidden=config.authorised;$('demo-button').hidden=config.requireJev;$('creation-note').textContent=config.jev?((config.jevProvider==='jev-ai'?'Jev AI':'TypeSafe Jev')+' shapes the personality. Create builds a detailed custom companion with Tripo and Blender.'):'Local design demo · included pets have detailed models.';$('tripo-start').disabled=!config.tripo||!config.finishing;$('tripo-note').textContent=config.tripo?'Tripo is connected. Each approved stage uses credits. Animation finishing runs locally.':'Optional Tripo connection is not configured. The main creator works without it.';if(config.tripo&&config.authorised){try{const balance=await api('/api/tripo/balance');$('tripo-note').textContent=`${balance.available} Tripo API credits available. Reference: about 10 credits; detailed mesh, rig and walk: about 75 more.`;$('tripo-start').disabled=balance.available<10||!config.finishing;if(!config.finishing)$('tripo-note').textContent='Install Blender and set BLENDER_PATH to enable detailed creation. No credits have been spent.';}catch(e){$('tripo-note').textContent=e.message;$('tripo-start').disabled=true;}}}
$('unlock').addEventListener('click',async()=>{try{await api('/api/session',{code:$('access-code').value});$('access-code').value='';await connect();toast('Workshop unlocked.');}catch(e){toast(e.message);}});
function savePet(){if(pet.source==='sample')return;saved=saved.filter(p=>!(p.name===pet.name&&p.description===pet.description));saved.unshift({...pet});saved=saved.slice(0,12);try{localStorage.setItem('creature-pets',JSON.stringify(saved));}catch{toast('Your browser could not save this pet. You can still play.');}renderSaved();}
function renderSaved(){const container=$('saved-pets');container.replaceChildren();const items=saved.length?saved:PRESETS.map(p=>({...p,source:'sample'}));for(const item of items){const button=document.createElement('button');button.className='saved-card';const icon=document.createElement('span');icon.className='saved-icon';icon.innerHTML=paw;const colours={cream:'#e7dcc8',caramel:'#ce986e',charcoal:'#727c90',lilac:'#b8a4d1',moss:'#98b394'};icon.style.color=colours[item.design.coat];const label=document.createElement('span');const name=document.createElement('b');name.textContent=item.name;const trait=document.createElement('small');trait.textContent=`${item.design.personality} ${item.design.family}${item.source==='sample'?' · sample':''}`;label.append(name,trait);const arrow=document.createElement('span');arrow.textContent='↗';button.append(icon,label,arrow);button.addEventListener('click',()=>{setPet(item);$('pet-name').value=item.name;$('pet-description').value=item.description;toast(`${item.name} is ready to play.`);});container.append(button);}}
async function useGeneratedAsset(url,name,revision=petRevision){url=currentModelUrl(url);$('room-button').disabled=true;$('model-loading').hidden=false;$('preview-tag').textContent='LOADING DETAILED PET';try{const asset=await loadCreatureAsset(url);if(revision!==petRevision)return;const creature=createImportedCreature(asset);studio.useCreature(creature);externalPet={asset,url};pet.modelUrl=url;pet.name=name;motion.react('Greet',4);$('preview-tag').textContent='AI-GENERATED 3D';$('preview-name').firstChild.textContent=`Meet ${name} `;$('pet-trait').textContent='Detailed companion · Tripo mesh';}finally{if(revision===petRevision){$('room-button').disabled=false;$('model-loading').hidden=true;}}}
function setPet(next){pet={...next,design:validateDesign(next.design)};petRevision++;$('model-loading').hidden=true;motion=new PetMotion();motion.mood=pet.design.personality;lastDecision=0;externalPet=null;studio.replace(pet.design);$('room-button').disabled=false;$('preview-name').replaceChildren(document.createTextNode(`Meet ${pet.name} `));const star=document.createElement('span');star.textContent='✦';$('preview-name').append(star);$('pet-trait').textContent=`${pet.design.personality[0].toUpperCase()+pet.design.personality.slice(1)} little ${pet.design.family}`;$('preview-tag').textContent=pet.source==='jev'?'DESIGN PREVIEW':pet.source==='sample'?'SAMPLE COMPANION':'LOCAL DESIGN DEMO';$('follow-button').setAttribute('aria-pressed','false');$('block-button').setAttribute('aria-pressed','false');blockMode=false;studio.obstacles([]);renderSaved();renderMood();const modelUrl=pet.modelUrl||includedModel(pet.design,pet.description);if(modelUrl)useGeneratedAsset(modelUrl,pet.name).catch(()=>{$('preview-tag').textContent='PROCEDURAL FALLBACK';toast('The detailed asset could not load. Showing a simple fallback; reload to retry.');});}
function decisionPanel(result){$('brain-source').textContent=result.source==='jev'?'Jev connected':'Local behaviour';const container=$('decision-body');container.replaceChildren();const note=document.createElement('p');note.textContent=result.note;container.append(note);if(result.probabilities){for(const [action,value]of Object.entries(result.probabilities).sort((a,b)=>b[1]-a[1])){const row=document.createElement('div');row.className='decision-row';const text=document.createElement('span');text.textContent=LABELS[action]||action;const bar=document.createElement('i');bar.style.width=(value*100)+'%';const figure=document.createElement('b');figure.textContent=Math.round(value*100)+'%';row.append(text,bar,figure);container.append(row);}const footer=document.createElement('small');footer.textContent=`Decision confidence ${Math.round(result.confidence*100)}% · model probabilities`;container.append(footer);}}
async function choose(){if(motion.expressionRemaining>0||pendingDecision||document.hidden||!config?.authorised||motion.tracking==='lost')return;pendingDecision=true;const revision=petRevision,epoch=motion.requestEpoch;const state=motion.snapshot(pet.design.personality,personInView());try{const result=await api('/api/decision',state);if(revision!==petRevision||epoch!==motion.requestEpoch||motion.expressionRemaining>0)return;decisionPanel(result);if(result.confidence!==null&&result.confidence<.12)return;if(allowedActions(motion.snapshot()).includes(result.action)&&result.action!==motion.action)motion.setAction(result.action);}catch(e){if(config?.requireJev){$('brain-source').textContent='Jev unavailable';}else if(revision===petRevision&&epoch===motion.requestEpoch){const result=fallbackDecision(state);result.note='Local fallback · connection unavailable';decisionPanel(result);if(result.action!==motion.action)motion.setAction(result.action);}}finally{pendingDecision=false;}}
let personVisible=false,personSeenAt=0;
const personInView=()=>personVisible&&performance.now()-personSeenAt<4000;
function tick(dt,view){if(!room){motion.viewer={x:view.camera.position.x,z:view.camera.position.z};}motion.update(dt);if(view)view.sync(motion,dt);
  const now=performance.now();if(now-lastDecision>3000&&motion.age>1.8){lastDecision=now;choose();}if(now-lastUi>180){lastUi=now;$('action-label').textContent=motion.expression?({Curious:'A curious head tilt',Playful:'Ready to play',Shy:'Feeling a little shy',Sleepy:'Sleepy little nods',Greet:'A paw just for you',Stretch:'A lovely long stretch'}[motion.expression]):LABELS[motion.action];$('energy-value').textContent=Math.round(motion.energy)+'%';$('energy-fill').style.width=motion.energy+'%';}}
function tap(p){if(blockMode){if(motion.obstacles.length>=6){toast('Six exclusions is the limit for this small play area.');return;}if(motion.addObstacle({x:p.x,z:p.z,w:.4,d:.4})){studio.obstacles(motion.obstacles);room?.obstacles(motion.obstacles);toast('Marked a small exclusion zone.');}else toast('Place the obstacle away from your companion.');return;}if(!motion.setBall(p))toast('Tap inside the play area, away from obstacles.');}
studio=new Studio($('studio'),pet.design,{onTap:tap,frame:tick});
function renderMood(){document.querySelectorAll('[data-mood]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mood===motion.mood)));}
function reaction(clip,note,seconds=clip==='Greet'||clip==='Playful'?4:5){if(!motion.react(clip,seconds))return;$('follow-button').setAttribute('aria-pressed','false');$('room-follow').setAttribute('aria-pressed','false');$('mood-note').textContent=note;toast(note);}
document.querySelectorAll('[data-mood]').forEach(button=>button.addEventListener('click',()=>{motion.setMood(button.dataset.mood);renderMood();$('follow-button').setAttribute('aria-pressed','false');$('room-follow').setAttribute('aria-pressed','false');$('mood-note').textContent=button.textContent+' body language · a performed mood, just for play.';}));
$('greet-button').addEventListener('click',()=>reaction('Greet','Hello! Watch that little paw.'));
$('pet-button').addEventListener('click',()=>reaction('Curious','A soft head tilt and a little attention.'));
$('stretch-button').addEventListener('click',()=>reaction('Stretch','Front paws out. Time for a stretch.'));
const follow=()=>{motion.follow=!motion.follow;motion.requestEpoch++;motion.setAction(motion.follow?'follow':'look');$('follow-button').setAttribute('aria-pressed',String(motion.follow));$('room-follow').setAttribute('aria-pressed',String(motion.follow));toast(motion.follow?'Your companion will follow the phone camera.':'Free to explore again.');};
const throwBall=()=>{blockMode=false;$('block-button').setAttribute('aria-pressed','false');if(room){toast('Tap a clear spot on the floor to throw the virtual ball.');return;}const p={x:(Math.random()-.5)*1.8,z:(Math.random()-.5)*1.8};if(!motion.setBall(p))toast('Try tapping a clear spot in the play area.');};
$('ball-button').addEventListener('click',throwBall);$('room-ball').addEventListener('click',throwBall);$('follow-button').addEventListener('click',follow);$('room-follow').addEventListener('click',follow);$('rest-button').addEventListener('click',()=>{motion.follow=false;motion.ball=null;motion.setAction('rest');$('follow-button').setAttribute('aria-pressed','false');});
function toggleBlock(){blockMode=!blockMode;$('block-button').setAttribute('aria-pressed',String(blockMode));toast(blockMode?'Tap the floor to mark a small area your pet should avoid.':'Tap the floor to throw a virtual ball.');}
$('block-button').addEventListener('click',toggleBlock);$('room-greet').addEventListener('click',()=>reaction('Greet','Hello from your companion.'));$('room-playful').addEventListener('click',()=>reaction('Playful','An invitation to play.'));$('room-sleepy').addEventListener('click',()=>reaction('Sleepy','A sleepy little pause.',6));$('room-block').addEventListener('click',toggleBlock);$('reset-view').addEventListener('click',()=>studio.resetCamera());
document.querySelectorAll('[data-preset]').forEach(button=>button.addEventListener('click',()=>{const preset=PRESETS.find(p=>p.name===button.dataset.preset);$('pet-name').value=preset.name;$('pet-description').value=preset.description;setPet({...preset,source:'sample'});$('form-status').textContent='Detailed sample loaded. Describe a new companion to create your own.';}));
async function createPet(local=false){const button=$('create-button');button.disabled=true;$('demo-button').disabled=true;$('form-status').textContent='Dreaming up your companion…';try{const result=await api('/api/design',{name:$('pet-name').value,description:$('pet-description').value,...(local?{mode:'local'}:{})});if(!local&&config?.tripo&&!includedModel(result.design,result.description)){
 if(!config.finishing)throw new Error('Install Blender and set BLENDER_PATH before detailed creation. No Tripo credits were spent.');
 pendingBrief=result;$('upgrade').open=true;await startGeneration(result);$('form-status').textContent='Review the artwork below before approving the 3D build. Your current companion stays here while it is created.';
 }else{setPet(result);savePet();$('form-status').textContent=result.note+(local?' · simple procedural preview':!includedModel(result.design,result.description)?' · simple design preview; connect Tripo and Blender for a detailed character':'');toast(result.name+' is here. Say hello.');}}catch(error){$('form-status').textContent=error.message;}finally{button.disabled=false;$('demo-button').disabled=false;}}
$('pet-form').addEventListener('submit',e=>{e.preventDefault();createPet();});
$('demo-button').addEventListener('click',()=>{if($('pet-form').reportValidity())createPet(true);});
async function enterRoom(){if(!mobileARSupport()){toast('Open this same website on an iPhone or Android phone to use the room camera.');return;}$('room-view').hidden=false;document.body.classList.add('in-room');studio.pause();motion.path=[];motion.ball=null;motion.obstacles=[];studio.obstacles([]);const asset=externalPet?.asset;room=new RoomSession({canvas:$('room-canvas'),design:pet.design,motion,onStatus:message=>$('room-instruction').textContent=message,onTap:tap,onFrame:dt=>tick(dt,null),createPet:asset?()=>createImportedCreature(asset):undefined});const session=room;try{await session.start();}catch(e){if(room===session){await exitRoom();toast(e.message);}}}
async function exitRoom(){stopPerception();await room?.stop();room=null;$('room-view').hidden=true;document.body.classList.remove('in-room');motion.position={x:0,z:0};motion.obstacles=[];motion.ball=null;motion.path=[];studio.obstacles([]);studio.resume();}
$('room-button').addEventListener('click',enterRoom);$('exit-room').addEventListener('click',exitRoom);$('room-recenter').addEventListener('click',()=>room?.recenter());
if(!mobileARSupport())$('room-note').textContent='Room mode is for iPhone and Android. Open this website on your phone; explore the 3D preview here.';
document.addEventListener('visibilitychange',()=>{motion.requestEpoch++;if(document.hidden){motion.tracking='lost';room?.XR8?.pause();}else{motion.tracking=room?'lost':'normal';room?.XR8?.resume();}});
// Optional local perception; enabled explicitly to keep the camera loop light.
let perception=null;
async function startPerception(){if(perception){stopPerception();return;}if(!room?.video||typeof createImageBitmap!=='function'||typeof OffscreenCanvas==='undefined'){toast('Local vision needs a ready camera and a browser with OffscreenCanvas.');return;}perception=new Perception({video:room.video,onResult:visible=>{personVisible=visible;personSeenAt=performance.now();},onStatus:toast});$('room-vision').setAttribute('aria-pressed','true');}
function stopPerception(){personVisible=false;perception?.stop();perception=null;$('room-vision').setAttribute('aria-pressed','false');}
$('room-vision').addEventListener('click',startPerception);
async function pollGeneration(){clearTimeout(generationTimer);if(!generation)return;try{generation=await api(`/api/generations/${generation.id}`);localStorage.setItem('creature-generation',generation.id);$('generation-status').textContent=generation.error||(generation.status==='complete'?(generation.quality?.faceReviewRequired?'Ready · 13 living animations. The jaw fit is estimated: check Sleepy and Hello before sharing.':'Ready · detailed companion with 13 living animations.'):generation.stage==='finish'?'Adding body motion, expressions and stepping turns locally…':`${generation.stage} · ${generation.status}`);if(generation.imageUrl){$('reference-image').src=generation.imageUrl;$('reference-image').hidden=false;}$('approve-reference').hidden=generation.status!=='awaiting_approval';$('use-model').hidden=generation.status!=='complete';$('retry-finish').hidden=generation.status!=='finish_failed';if(['running','submitting','finish_pending','processing'].includes(generation.status))generationTimer=setTimeout(pollGeneration,3000);}catch(e){$('generation-status').textContent=e.message;}}
async function startGeneration(brief){
 if(generationStarting)throw new Error('A reference request is already being submitted.');
 if(generation&&['running','submitting','awaiting_approval','processing','finish_pending','uncertain'].includes(generation.status))throw new Error('An existing generation is still open. Finish or review it before starting another paid request.');
 generationStarting=true;try{generation=await api('/api/generations',brief);await pollGeneration();}finally{generationStarting=false;}
}
$('tripo-start').addEventListener('click',async()=>{if(!$('pet-form').reportValidity())return;const button=$('tripo-start');button.disabled=true;try{pendingBrief={name:$('pet-name').value,description:$('pet-description').value,design:pet.design,source:'generated'};await startGeneration(pendingBrief);}catch(e){$('generation-status').textContent=e.message;}finally{button.disabled=!config?.tripo||!config?.finishing;}});
$('retry-finish').addEventListener('click',async()=>{try{generation=await api(`/api/generations/${generation.id}/finish`,{});await pollGeneration();}catch(e){$('generation-status').textContent=e.message;}});
$('approve-reference').addEventListener('click',async()=>{const button=$('approve-reference');button.disabled=true;try{generation=await api(`/api/generations/${generation.id}/approve`,{});pollGeneration();}catch(e){$('generation-status').textContent=e.message;}finally{button.disabled=false;}});
$('use-model').addEventListener('click',async()=>{try{pet={...(pendingBrief||pet),name:generation.name,description:generation.description||pendingBrief?.description||pet.description,source:'generated',design:pendingBrief?.design||localDesign(generation.description||pet.description)};petRevision++;motion=new PetMotion();await useGeneratedAsset(generation.modelUrl,generation.name);savePet();toast('Your generated companion is ready for the preview and room camera.');}catch(e){toast(e.message);}});
setPet(pet);connect().then(()=>{const id=localStorage.getItem('creature-generation');if(id&&config.tripo&&config.authorised){generation={id};pollGeneration();}}).catch(e=>{$('creation-note').textContent='Connection unavailable · sample companion is ready to play.';toast(e.message);});
// Read-only hooks for verification and deterministic capture of the actual app.
window.creatureLab={framing:()=>studio.framing(),roomAnimation:()=>room?.pet?.animationState?.(),snapshot:()=>({pet,motion:motion.snapshot(pet.design.personality),position:{...motion.position},yaw:motion.yaw,angularSpeed:motion.angularSpeed,obstacles:[...motion.obstacles],expression:motion.expression,expressionRemaining:motion.expressionRemaining,mood:motion.mood,external:!!externalPet,asset:{generated:!!studio.pet.generated,triangles:studio.pet.triangles,clips:studio.pet.clips().map(c=>c.name),animation:studio.pet.animationState?.()}}),pose:(mode='studio')=>{const bones=[];const g=(mode==='room'?room?.pet:studio.pet)?.group;if(!g)return bones;g.updateMatrixWorld(true);g.traverse(o=>{if(o.isBone)bones.push({name:o.name,q:o.quaternion.toArray(),world:o.matrixWorld.elements.slice(12,15)});});return bones;},capture:()=>studio.renderer.domElement.toDataURL('image/png'),exportGLB:async()=>new GLTFExporter().parseAsync(studio.pet.group,{binary:true,animations:studio.pet.clips()}),exportRecipe:()=>JSON.stringify({name:pet.name,description:pet.description,design:pet.design,modelUrl:pet.modelUrl},null,2)};

function download(data,type,name){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
$('download-pet').addEventListener('click',async()=>{try{if(externalPet){const response=await fetch(externalPet.url);if(!response.ok)throw new Error('Download failed');download(await response.arrayBuffer(),'model/gltf-binary','companion.glb');}else download(await window.creatureLab.exportGLB(),'model/gltf-binary','companion.glb');toast('Your animated 3D companion is ready.');}catch{toast('The 3D export could not finish. Please try again.');}});
$('download-recipe').addEventListener('click',()=>download(window.creatureLab.exportRecipe(),'application/json','companion-design.json'));
